spring:
  application:
    name: rest-Service # ==> This is Service-Id
     
 
---
# Items that apply to ALL profiles:   
eureka:
  instance:
    appname: rest-Service  # ==> This is a instance of REST-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
     defaultZone: http://myeurekaserver.com:9000/eureka/
server:
  port: 8080
  
---
spring:
  profiles: replica01
eureka:
  instance:
    appname: rest-Service  # ==> This is a instance of ABC-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://myeurekaserver.com:9000/eureka/ 
server:
  port: 8001   
     
---
spring:
  profiles: replica02
eureka:
  instance:
    appname: rest-Service  # ==> This is a instance of ABC-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://myeurekaserver.com:9000/eureka/
server:
  port: 8002
  
---
spring:
  profiles: replica03
eureka:
  instance:
    appname: rest-Service  # ==> This is a instance of ABC-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://myeurekaserver.com:9000/eureka/ 
server:
  port: 8003
  
---
spring:
  profiles: replica04
eureka:
  instance:
    appname: rest-Service  # ==> This is a instance of ABC-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://myeurekaserver.com:9000/eureka/ 
server:
  port: 8004  
  
---
spring:
  profiles: replica05
eureka:
  instance:
    appname: rest-Service  # ==> This is a instance of ABC-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://myeurekaserver.com:9000/eureka/ 
server:
  port: 8005